### ISSUE TITLE
Thread exception when updating event

### ISSUE THREAD

**Issue by svenpopping** [WISVCH/events#142]
```
java.lang.IllegalThreadStateException: null
	at java.lang.Thread.start(Thread.java:705) ~[?:1.8.0_102]
	at ch.wisv.events.core.webhook.WebhookPublisher.event(WebhookPublisher.java:79) ~[classes/:?]
	at ch.wisv.events.dashboard.controller.DashboardEventController.update(DashboardEventController.java:168) ~[classes/:?]
```

**Comment by praseodym** [comment]
Please don’t do stuff like `extends Thread`, it’s a recipe for disaster. See https://stackoverflow.com/questions/22474961/scenario-where-extending-thread-is-preferred-than-implement-runnable and preferably use something that Spring can manage for you.
